# Generated by Django 6.0.6 on 2026-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_bio_customuser_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
