# Generated by Django 6.0.6 on 2026-07-12 16:06

import django.db.models.deletion
import properties.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('have_documentation', models.BooleanField(default=False)),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('video_url', models.URLField(blank=True, null=True)),
                ('property_type', models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('villa', 'Villa'), ('land', 'Land'), ('commercial', 'Commercial'), ('office', 'Office')], default='apartment', max_length=30)),
                ('listing_type', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], default='rent', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('sold', 'Sold'), ('rented', 'Rented'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(default='Albania', max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=properties.models.property_image_upload_path)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('total_living_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bedrooms', models.PositiveIntegerField(default=0)),
                ('bathrooms', models.PositiveIntegerField(default=0)),
                ('floor', models.IntegerField(blank=True, null=True)),
                ('balcony', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('view', models.CharField(blank=True, max_length=250, null=True)),
                ('elevator', models.BooleanField(default=False)),
                ('furnishing_status', models.CharField(blank=True, choices=[('fully_furnished', 'Fully Furnished'), ('partially_furnished', 'Partially Furnished'), ('unfurnished', 'Unfurnished')], max_length=100, null=True)),
                ('heating_colling_system', models.CharField(blank=True, max_length=100, null=True)),
                ('parking_spots', models.PositiveIntegerField(default=0)),
                ('orientation', models.CharField(blank=True, max_length=100, null=True)),
                ('total_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True)),
                ('management_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('land_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('number_of_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('basement', models.BooleanField(default=False)),
                ('swimming_pool', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('security_system', models.BooleanField(default=False)),
                ('outdoor_extras', models.CharField(blank=True, max_length=250, null=True)),
                ('zoning_type', models.CharField(blank=True, choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial'), ('agricultural', 'Agricultural'), ('mixed_use', 'Mixed Use')], max_length=100, null=True)),
                ('road_frontage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('terrain_topography', models.CharField(blank=True, choices=[('flat', 'Flat'), ('hilly', 'Hilly'), ('mountainous', 'Mountainous'), ('valley', 'Valley'), ('coastal', 'Coastal'), ('island', 'Island')], max_length=100, null=True)),
                ('max_allowed_floors', models.PositiveIntegerField(blank=True, null=True)),
                ('road_access', models.CharField(blank=True, choices=[('asphalt', 'Asphalt'), ('dirt', 'Dirt'), ('no_public_access', 'No Public Access'), ('landlocked', 'Landlocked')], max_length=100, null=True)),
                ('utilities', models.TextField(blank=True, null=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='agency.agency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'properties',
                'ordering': ['-is_premium', '-date_updated'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=properties.models.property_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
