# Generated by Django 6.0.6 on 2026-07-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
